export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const LODING_DATA = "LODING_DATA";
export const ERROR_HANDLE = "ERROR_HANDLE";

export const  GET_DOCTORDATA = "GET_DOCTORDATA";
export const  ADD_DOCTORDATA = "ADD_DOCTORDATA";
export const  DELETE_DOCTORDATA = "DELETE_DOCTORDATA";
export const  EDIT_DOCTORDATA = "EDIT_DOCTORDATA";
